const express = require("express");
const topicRoutes = require("./Routes/topicRoutes");
const subscriberRoutes = require("./Routes/subscribeRoutes");
const eventRoutes = require("./Routes/eventRoutes");
const app = express();
app.use(express.json());
app.use("/topics", topicRoutes);
app.use("/subscribers", subscriberRoutes);
app.use("/events", eventRoutes);
module.exports = app;
